# Setup
title: kimtoma
url: https://kimtoma.com
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: UA-163781427-1

# Specify the author for blog posts
author:
  name: Kim Kyungsoo
  url: https://twitter.com/kimtoma
  email: kimtoma@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Projects
    url: /projects

  - title: Archive
    url: /archive

  - title: About
    url: /about
    

